repos:
# Python
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
    -   id: autopep8
        exclude: seqmuncher_0.97.2.py # Excluding script written by client
# R
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.3.2.9001
  hooks:
  - id: lintr
# Docker
- repo: https://github.com/AleksaC/hadolint-py
  rev: v2.10.0
  hooks:
    - id: hadolint
# General
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  -   id: check-added-large-files
      args: ['--maxkb=200']
